#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Install necessary packages

apt-get update > /dev/null 2>&1

apt install curl mediainfo sqlite3 wget libicu-dev -y > /dev/null 2>&1

rm -rf /app

wget --content-disposition 'http://radarr.servarr.com/v1/update/master/updatefile?os=linux&runtime=netcore&arch=x64' > /dev/null 2>&1

tar -xvzf Radarr*.linux*.tar.gz > /dev/null 2>&1

mkdir -p /config /data /app

mv Radarr /app

# Create user

adduser --disabled-login --no-create-home --gecos "" radarr > /dev/null 2>&1
groupmod -o -g "$PGID" radarr > /dev/null 2>&1
usermod -o -u "$PUID" radarr > /dev/null 2>&1

# Fix permissions

chown -R radarr:radarr /config /data /app

# Cleanup 

apt remove software-properties-common apt-utils -y > /dev/null 2>&1 && apt-get autoremove -y > /dev/null 2>&1 && apt clean > /dev/null 2>&1 && rm -rf /tmp/* /var/lib/apt/lists/* /var/tmp/* /Radarr*.linux*.tar.gz
